// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
// Generated by Table Code Generator.
// DO NOT EDIT THIS FILE MANUALLY.
// -----------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections.Generic;
using System.Linq;

namespace ClimbGames
{
    [Serializable]
    public partial class CharacterTable : Table<CharacterTableRecord>
    {
        // key: id
        protected Dictionary<uint, CharacterTableRecord> dictionary;

        public IReadOnlyList<CharacterTableRecord> Datas => datas;

        public override sealed void Initialize()
        {
            dictionary = datas.ToDictionary(x => x.Id);
            
            OnInitialized();
        }

        public bool TryGetValue(uint key, out CharacterTableRecord value) => dictionary.TryGetValue(key, out value);
    
        public static CharacterTable FromBytes(byte[] bytes) => CreateInstance<CharacterTable>().Load(bytes) as CharacterTable;
    }
}