// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
// Generated by Table Code Generator.
// DO NOT EDIT THIS FILE MANUALLY.
// -----------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections.Generic;
using System.Linq;

namespace ClimbGames
{
    [Serializable]
    public partial class ConfigTable : Table<ConfigTableRecord>
    {
        // key: ip
        // value: port
        protected Dictionary<string, int> dictionary;

        public IReadOnlyList<ConfigTableRecord> Datas => datas;

        public override sealed void Initialize()
        {
            dictionary = datas.ToDictionary(x => x.Ip, x => x.Port);
            
            OnInitialized();
        }

        public bool TryGetValue(string key, out int value) => dictionary.TryGetValue(key, out value);
    
        public static ConfigTable FromBytes(byte[] bytes) => CreateInstance<ConfigTable>().Load(bytes) as ConfigTable;
    }
}