// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
// Generated by Table Code Generator.
// DO NOT EDIT THIS FILE MANUALLY.
// -----------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections.Generic;
using System.IO;
using ClimbGames;

namespace ClimbGames
{
    [Serializable]
    public partial class ConfigTableRecord : TableRecord
    {
        [SerializeField] private string ip;
        [SerializeField] private int port;
        [SerializeField] private string etc;

        public string Ip => ip;
        public int Port => port;
        public string Etc => etc;

        public override void Read(BinaryReader br)
        {
            ip = br.ReadString();
            port = br.ReadInt32();
            etc = br.ReadString();
        }

        public override void Write(BinaryWriter bw)
        {
            bw.Write(ip ?? string.Empty);
            bw.Write(port);
            bw.Write(etc ?? string.Empty);
        }
    }
}