// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
// Generated by Table Code Generator.
// DO NOT EDIT THIS FILE MANUALLY.
// -----------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections.Generic;
using System.IO;

namespace ClimbGames
{
    [Serializable]
    public partial class MonsterTableRecord : TableRecord
    {
        [SerializeField] private uint id;
        [SerializeField] private string name;
        [SerializeField] private string desc;
        [SerializeField] private MonsterType type;
        [SerializeField] private int level;
        [SerializeField] private List<EquipType> items;

        public uint Id => id;
        public string Name => name;
        public string Desc => desc;
        public MonsterType Type => type;
        public int Level => level;
        public List<EquipType> Items => items;

        public override void Read(BinaryReader br)
        {
            id = br.ReadUInt32();
            name = br.ReadString();
            desc = br.ReadString();
            type = (MonsterType)br.ReadInt32();
            level = br.ReadInt32();
            items = new();
            int itemsCount = br.ReadInt32();
            for (int i = 0; i < itemsCount; ++i)
                items.Add((EquipType)br.ReadInt32());
        }

        public override void Write(BinaryWriter bw)
        {
            bw.Write(id);
            bw.Write(name ?? string.Empty);
            bw.Write(desc ?? string.Empty);
            bw.Write((int)type);
            bw.Write(level);
            int itemsCount = items != null ? items.Count : 0;
            bw.Write(itemsCount);
            for (int i = 0; i < itemsCount; ++i)
                bw.Write((int)items[i]);
        }
    }
}