// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
// Generated by Table Code Generator.
// DO NOT EDIT THIS FILE MANUALLY.
// -----------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections.Generic;

namespace ClimbGames
{
    [Serializable]
    public partial class MonsterTable : Table<MonsterTableRecord>
    {
        public override sealed void Initialize()
        {
            OnInitialized();
        }

        public MonsterTableRecord GetData(int index)
        {
            return index >= 0 && index < datas.Count ? datas[index] : null;
        }
    }
}