// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
// Generated by Table Code Generator.
// DO NOT EDIT THIS FILE MANUALLY.
// -----------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;
using ClimbGames;

namespace ClimbGames
{
    public static partial class Tables
    {
        public static CharacterTable Character { get; private set; }
        public static ConfigTable Config { get; private set; }
        public static MonsterTable Monster { get; private set; }

        public static void Load(string label)
        {
            var tables = AssetManager.LoadAssets<Table>(label);
            Load(tables);
        }

        public static async UniTask LoadAsync(string label)
        {
            var tables = await AssetManager.LoadAssetsAsync<Table>(label);
            Load(tables);
        }

        public static void Load<T>(string label) where T : TextAsset
        {
            var tables = AssetManager.LoadAssets<T>(label);
            Load(tables);
        }

        public static async UniTask LoadAsync<T>(string label) where T : TextAsset
        {
            var tables = await AssetManager.LoadAssetsAsync<T>(label);
            Load(tables);
        }

        public static void Load(IList<Table> tables)
        {
            foreach (var table in tables)
            {
                table.Initialize();
                switch (table)
                {
                    case CharacterTable value: Character = value; break;
                    case ConfigTable value: Config = value; break;
                    case MonsterTable value: Monster = value; break;
                }
            }
        }

        public static void Load<T>(IList<T> assets) where T : TextAsset
        {
            foreach (var asset in assets)
            {
                switch (asset.name)
                {
                    case "Character": Character = Tables<CharacterTable>.FromBytes(asset.bytes); break;
                    case "Config": Config = Tables<ConfigTable>.FromBytes(asset.bytes); break;
                    case "Monster": Monster = Tables<MonsterTable>.FromBytes(asset.bytes); break;
                }
            }
        }
    }
}