// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
// Generated by Table Code Generator.
// DO NOT EDIT THIS FILE MANUALLY.
// -----------------------------------------------------------------------------

using System;
using UnityEngine;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

namespace ClimbGames
{
    public static partial class Tables
    {
        public static CharacterTable Character { get; private set; }
        public static ConfigTable Config { get; private set; }

        public static void Load(string label)
        {
            var tables = AssetManager.LoadAssets<ITable>(label);
            Load(tables);
        }

        public static async UniTask LoadAsync(string label)
        {
            var tables = await AssetManager.LoadAssetsAsync<ITable>(label);
            Load(tables);
        }

        public static void Load<T>(string label) where T : TextAsset
        {
            var tables = AssetManager.LoadAssets<T>(label);
            Load(tables);
        }

        public static async UniTask LoadAsync<T>(string label) where T : TextAsset
        {
            var tables = await AssetManager.LoadAssetsAsync<T>(label);
            Load(tables);
        }

        public static void Load(IList<ITable> tables)
        {
            foreach (var table in tables)
            {
                table.Initialize();
                switch (table)
                {
                    case CharacterTable value: Character = value; break;
                    case ConfigTable value: Config = value; break;
                }
            }
        }

        public static void Load<T>(IList<T> assets) where T : TextAsset
        {
            foreach (var asset in assets)
            {
                switch (asset.name)
                {
                    case "Character": Character = CharacterTable.FromBytes(asset.bytes); break;
                    case "Config": Config = ConfigTable.FromBytes(asset.bytes); break;
                }
            }
        }
    }
}