// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE
// Generated by Table Code Generator.
// DO NOT EDIT THIS FILE MANUALLY.
// -----------------------------------------------------------------------------

namespace ClimbGames
{
    public enum CharacterType
    {
        None,
        Player,
        NPC,
        Monster,
    }

    public enum ItemType
    {
        Potion,
        Weapon,
        Equip,
    }

    public enum EquipType
    {
        Potion,
        Weapon,
        Equip,
    }
}